DjangoWebsite/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('repository/', include('PatternBuddy.urls', namespace='repository')),
    path('', include('PatternBuddy.urls', namespace='repository'))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

PatternBuddy/urls.py
from django.urls import path

from . import views

app_name = 'repository'
urlpatterns = [
    path('', views.IndexListView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('submit/', views.submit, name='submit'),
    path('save-to-xlsx', views.save_to_xlsx, name='save-to-xlsx')

]

PatternBuddy/models.py
from django.db import models


# Create your models here.

class Language(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Repository(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    name = models.CharField(max_length=200)
    full_name = models.CharField(max_length=200)
    last_checked = models.DateField(auto_now=True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    pull_request_count = models.PositiveIntegerField(default=0)
    comments_count = models.PositiveIntegerField(default=0)
    contributors_count = models.PositiveIntegerField(default=0)
    size = models.PositiveIntegerField(default=0)
    dp_count = models.PositiveIntegerField(default=0)
    dp_analyzed = models.BooleanField(default=False)

    def get_contributions(self):
        return Contribution.objects.filter(repository=self)

    def get_comment_pr_ratio(self):
        return self.comments_count / self.pull_request_count if self.pull_request_count else 0

    def get_dp_count(self):
        return self.patterninrepo_set.count()

    class Meta:
        verbose_name_plural = "repositories"

    def __str__(self):
        return self.full_name


class DesignPattern(models.Model):
    design_name = models.CharField(max_length=50)

    def __str__(self):
        return self.design_name


class Contributor(models.Model):
    login = models.CharField(max_length=200)
    followers_count = models.PositiveIntegerField(default=0)
    commits_count = models.PositiveIntegerField(default=0)
    url = models.URLField()

    def __str__(self):
        return self.login


class Contribution(models.Model):
    contributor = models.ForeignKey(Contributor, on_delete=models.CASCADE)
    repository = models.ForeignKey(Repository, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "Contribution of " + str(self.contributor) + " on " + str(self.repository)


class PatternInRepo(models.Model):
    design_pattern = models.ForeignKey(DesignPattern, on_delete=models.CASCADE)
    repository = models.ForeignKey(Repository, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "patterns in repos"

    def __str__(self):
        return "Pattern: " + str(self.design_pattern) + " in Repository: " + \
               str(self.repository)


class ClassFileWithPattern(models.Model):
    modifications_count = models.PositiveIntegerField(default=1)
    pattern_in_repo = models.ForeignKey(PatternInRepo, on_delete=models.CASCADE)
    class_name = models.CharField(max_length=200, default="ClassName")
    url = models.URLField(default="https://github.com")
    role = models.CharField(max_length=200, default="role")

    def __str__(self):
        return "File " + self.class_name + " has pattern " + self.pattern_in_repo.design_pattern.design_name

PatternBuddy/views.py
import logging

from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect, HttpResponse
# Create your views here.
from django.urls import reverse
from django.views import generic
from excel_response import ExcelResponse

from PatternBuddy.models import Repository
from PatternBuddy.repository_loader import load_from_github, analyze_repo, get_repo_api

logger = logging.getLogger(__name__)


class IndexListView(generic.ListView):
    model = Repository
    context_object_name = 'recent_repo_list'
    queryset = Repository.objects.all()
    template_name = "PatternBuddy/index.html"


class DetailView(generic.DetailView):
    model = Repository
    template_name = 'PatternBuddy/repository.html'


def submit(request):
    repository_name = request.POST['repo_textfield']
    logger.warning("repo_name = " + repository_name)
    try:
        repository = Repository.objects.get(full_name__icontains=repository_name)
        logger.debug("Repo found")
    except ObjectDoesNotExist:
        repository = load_from_github(repository_name=repository_name)
        if repository is None:
            return HttpResponse("The repository you entered does not exist")
    if not repository.dp_analyzed:
        analyze_repo(get_repo_api(repository_name), repository)
    return HttpResponseRedirect(reverse('repository:detail', args=(repository.id,)))


def save_to_xlsx(request):
    data = Repository.objects.all()
    return ExcelResponse(data, "data_socialpatterns")

PatternBuddy/templates/PatternBuddy/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.png' %}">

    <title>Social Patterns</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            {% url 'repository:index' as index_url %}
            <li class="nav-item {% if request.path == index_url %}active{% endif %}">
                <a class="nav-link" href="{{ index_url }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/admin">Admin</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="{% url 'repository:index' %}">Repository</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'repository:submit' %}" method="post">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search"
                   name="repo_textfield" id="repository_url">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

<main role="main" class="container">

    <div class="starter-template">

        {% block content %}
        {% endblock %}

    </div>

</main><!-- /.container -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/jquery-3.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>

PatternBuddy/templates/PatternBuddy/index.html
{% extends 'PatternBuddy/base.html' %}
{% block content %}
    <h1>Repository Loader</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <div class="row ">

        <div class="col-6 offset-3 ">
            <form action="{% url 'repository:submit' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="repository_url">Enter repository name</label>
                    <input class="form-control" type="text" name="repo_textfield" id="repository_url"/>
                    <input class="btn btn-primary mt-2" type="submit" value="Search"/>
                </div>

            </form>
        </div>

    </div>

    <div class="row">

        <div class="col-6 offset-3">

            <h2>Recent repositories analyzed</h2>
            <div class="row">
                {% if recent_repo_list %}

                    <ul class="list-group">

                        {% for repo in recent_repo_list %}
                            <li class="list-group-item">
                                <a href="{% url 'repository:detail' repo.id %}">{{ repo.full_name }}</a>
                            </li>
                        {% endfor %}

                    </ul>
                {% else %}
                    <p>There are no repositories analyzed.</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-3">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Download as Excel</h4>
                    <a href="{% url 'repository:save-to-xlsx' %}" class="card-link">Click here</a>
                </div>
            </div>
        </div>

    </div>


{% endblock %}

PatternBuddy/templates/PatternBuddy/repository.html
{% extends 'PatternBuddy/base.html' %}
{% block content %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


    <h1>{{ object.full_name }} <span class="badge badge-success">{{ object.language }}</span></h1>

    <div class="row">
        <div class="col-6">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <h3>Design Patterns</h3>
                    <table class="table table-bordered">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">Pattern Name</th>
                            {#                            <th scope="col">File</th>#}
                            {#                            <th scope="col">Role</th>#}
                        </tr>
                        </thead>
                        <tbody>
                        {% for dp in repository.patterninrepo_set.all %}
                            <tr>
                            <td>{{ dp.design_pattern }}</td>

                            {% comment %}{% for classfile in dp.classfilewithpattern_set.all %}

                                    {% if classfile != dp.classfilewithpattern_set.all.0 %}
                                        <tr>
                                    {% endif %}
                                <td>{{ classfile.url }}</td>
                                <td>{{ classfile.role }}</td>
                                </tr>

                                {% endfor %}{% endcomment %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
        <div class="col-6">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <h3>Repository stats</h3>
                    <div class="card-group">
                        <div class="card">
                            <div class="card-block">
                                <h5 class="card-title bg-primary text-white">Pull Requests</h5>
                                <p class="card-text">{{ object.pull_request_count }}</p>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-block">

                                <h5 class="card-title bg-primary text-white">Comments/PR</h5>
                                <p class="card-text"> {{ object.get_comment_pr_ratio }}</p>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-block">
                                <h5 class="card-title bg-primary text-white">Comments</h5>
                                <p class="card-text">{{ object.comments_count }}</p>
                            </div>
                        </div>
                    </div>


                    <div class="card-group">
                        <div class="card">
                            <div class="card-block">
                                <h5 class="card-title bg-primary text-white">Contributors</h5>
                                <p class="card-text">{{ object.contributors_count }}</p>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-block">

                                <h5 class="card-title bg-primary text-white">Size</h5>
                                <p class="card-text"> {{ object.size }}</p>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-block">
                                <h5 class="card-title bg-primary text-white">DP Count</h5>
                                <p class="card-text">{{ object.get_dp_count }}</p>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <h3>Contributors </h3>
                    {% if repository.contribution_set.all %}

                        <table class="table">
                            <thead>
                            <tr>
                                <th>User Login</th>
                                <th>Contributions #</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for contribution in repository.contribution_set.all %}
                                <tr>
                                    <td>
                                        <a href="{{ contribution.contributor.url }}">{{ contribution.contributor.login }}</a>
                                    </td>
                                    <td>{{ contribution.amount }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <p>
                            Contributions were not collected for this project
                        </p>
                    {% endif %}
                </div>


            </div>
        </div>

    </div>

{% endblock %}